# Generated by Django 2.1.7 on 2019-08-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=245101)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('whoto', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('phone', models.IntegerField(default=9897654568)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_perma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=245101)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('whoto', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('phone', models.IntegerField(default=9897654568)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
