# Generated by Django 2.1.7 on 2019-08-06 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_perma',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visitor_perma',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='visitor_perma',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor_perma',
            name='whoto',
            field=models.CharField(max_length=50),
        ),
    ]
