# Generated by Django 2.0.2 on 2019-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='image',
        ),
        migrations.AlterField(
            model_name='temp',
            name='address',
            field=models.TextField(default='abes-ghzb'),
        ),
        migrations.AlterField(
            model_name='temp',
            name='name',
            field=models.CharField(default='nec', max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='uid',
            field=models.IntegerField(default=123),
        ),
    ]
