# Generated by Django 2.0.2 on 2019-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190717_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='gender',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='temp',
            name='pincode',
            field=models.IntegerField(default=24510),
        ),
        migrations.AlterField(
            model_name='temp',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
