# Generated by Django 2.0.2 on 2019-07-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190718_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_perma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='m', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=245101)),
                ('purpose', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='temp',
            name='purpose',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='temp',
            name='pincode',
            field=models.IntegerField(default=245101),
        ),
    ]
