# Generated by Django 2.0.2 on 2019-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190719_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='visitor_perma',
            name='gender',
        ),
        migrations.AddField(
            model_name='temp',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='temp',
            name='phone',
            field=models.IntegerField(default=9897654568),
        ),
        migrations.AddField(
            model_name='temp',
            name='whoto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='phone',
            field=models.IntegerField(default=9897632545),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='whoto',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
