# Generated by Django 2.0.2 on 2019-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190730_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='whoto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='whoto',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
