# Generated by Django 2.0.2 on 2019-08-02 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190730_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='uid',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='visitor_perma',
            name='uid',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
