# Generated by Django 2.0.2 on 2019-08-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190802_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
